apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Petclinic pipeline
on:
  push:
    branches:
      - main
jobs:
  maven-build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: docker://maven:3-eclipse-temurin-17
        name: Maven build
        kind: build
        shell: sh
        run: |
          mvn clean verify -Dtest="*,!MySql*,!Postgres*"
  SonarQube:
    needs: maven-build
    steps:
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
  JFrog:
    needs: SonarQube
    steps:
      - name: Jfrog configure
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: testcbplatform
          username: ${{ vars.jfrogTestCBusername }}
          password: ${{ secrets.jfrogTestCBpassword }}
      - name: Push image to the configured OCI Registry
        uses: cloudbees-io/kaniko@v1
        with:
          destination: maven-pet-clinic-libs-snapshot
